### ISSUE TITLE
Tutorials

### ISSUE THREAD

**Issue by hugary1995** [hugary1995/raccoon#45]
- [x] Mode I: brittle fracture #35 
- [x] Mode II: brittle fracture #35 
- [x] cohesive fracture #36 
- [ ] fatigue #40 
- [x] pressurized fracture, include corrections to Gc and crack length #39 #42 
- [x] ductile fracture #38 
- [ ] dynamic fracture and time integrators
- [x] KL expansion and soil desiccation #41 
- [x] large deformation #37 
- [x] initial cracks
- [x] conditional element deletion
- [ ] coupling with xfem

**Comment by lyyc199586** [comment]
Did moose support xfem? Are there any examples repos on that?

**Comment by hugary1995** [comment]
Yeah, there is a module called xfem. Some example input files are in `moose/modules/xfem/test/tests`.

**Comment by lyyc199586** [comment]
Ok, then it should'nt be too hard to implement cutfem laser ablation, gona try it

**Comment by hugary1995** [comment]
@jiangwen84 , Hi Wen, @lyyc199586 is a first year PhD student in our group. I think he'll spend some time implementing the signirini condition with xfem. Could you give him some suggestions?

**Comment by jiangwen84** [comment]
No problem.   Feel free to send me emails or open a discussion on github if you have any questions.

**Comment by lyyc199586** [comment]
Thank you! and I am second year now 🤣
